# Generated by Django 2.1.2 on 2018-11-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0003_auto_20181105_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='averageGrade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='review',
            name='courseOfReview',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='university',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='university',
            name='subjectsOffered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='writtenReviews',
        ),
    ]
