# Generated by Django 2.1.1 on 2018-11-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0004_auto_20181113_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdooruser',
            name='major',
        ),
        migrations.AddField(
            model_name='classdooruser',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Subject'),
        ),
    ]
