# Generated by Django 2.1.1 on 2018-11-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0005_auto_20181113_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdooruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classdooruser',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
