# Generated by Django 2.1.2 on 2018-10-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0006_auto_20181018_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='subjectsOffered',
            field=models.ManyToManyField(blank=True, to='classdoor.Subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='writtenReviews',
            field=models.ManyToManyField(blank=True, to='classdoor.Review'),
        ),
    ]
