# Generated by Django 2.1.1 on 2018-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0006_auto_20181113_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classdooruser',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='classdooruser',
            name='username',
        ),
    ]
