# Generated by Django 2.1.2 on 2018-11-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0009_auto_20181116_0948'),
        ('classdoor', '0004_auto_20181105_2201'),
    ]

    operations = [
    ]
