# Generated by Django 2.1.2 on 2018-11-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0009_auto_20181116_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='gradeReceived',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b', 'B'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d', 'D-'), ('f', 'F')], max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='starRating',
            field=models.CharField(choices=[('.5', '.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], max_length=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('hard', 'Hard'), ('Interesting', 'Interesting'), ('boring', 'Boring'), ('attendence', 'Attendence Graded'), ('gen-ed', 'Gen-Ed'), ('professor', 'Great Professsor'), ('homework', 'Lots of Homework'), ('exam', 'Exam-Heavy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
