# Generated by Django 2.1.3 on 2018-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0010_auto_20181121_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='starRating',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=3),
        ),
    ]
