# Generated by Django 2.1.2 on 2018-11-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0012_auto_20181126_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, choices=[('easy', 'Easy'), ('hard', 'Hard'), ('Interesting', 'Interesting'), ('boring', 'Boring'), ('attendence', 'Attendence Graded'), ('gen-ed', 'Gen-Ed'), ('professor', 'Great Professsor'), ('homework', 'Lots of Homework'), ('exam', 'Exam-Heavy')], max_length=100)),
                ('courseOfTag', models.ForeignKey(help_text='Select a course for this description', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classdoor.Course')),
            ],
            options={
                'ordering': ['tags'],
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select tags for this class', to='classdoor.Tags'),
        ),
    ]
