# Generated by Django 2.1.2 on 2018-12-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0016_auto_20181205_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='starRating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
