# Generated by Django 2.1.2 on 2018-12-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdoor', '0017_auto_20181205_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='starRating',
            field=models.DecimalField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], decimal_places=1, max_digits=2),
        ),
    ]
